### ISSUE TITLE
how to train stage2 with cifar100?

### ISSUE THREAD

**Issue by abebe9849** [ml-jku/MIM-Refiner#3]
python main_train.py --devices 0,1 --hp /home/u094724e/aimed2022/MIM-Refiner/src/yamls/stage2/l16_d2v2_custom.yaml

```
#l16_d2v2_custom.yaml
datasets:
  train:
    template: ${yaml:datasets/cifar100/train_minaug_smooth}
    #template.vars.version: imagenet1k
  train_noaug_10p:
    template: ${yaml:datasets/cifar100/train_minaug_smooth}
    #template.vars.version: 
  test:
    template: ${yaml:datasets/cifar100/test_noaug}
    #template.vars.version: imagenet1k
```
>>>
  File "/home/u094724e/aimed2022/MIM-Refiner/src/trainers/contrastive_trainer.py", line 92, in forward
    assert not self.training
AssertionError

how can i solve this?

**Comment by BenediktAlkin** [comment]
Hi, 

the template "datasets/cifar100/train_minaug_smooth" is not a template for contrastive learning, i.e. it only has a single view and is ment for training a classifier. The assertion where it fails is thrown because during training, the ContrastiveTrainer expects to get a list of images and here it only gets a single image.

I added the corresponding templates (copying the templates of imagenet and changing the "kind" attribute to "cifar100") so you can now use the following yaml configuration for datasets:

```
datasets:
  train:
    template: ${yaml:datasets/cifar100/train_byolaug_globalviews}
  train_noaug_10p:
    template: ${yaml:datasets/cifar100/train_noaug}
  test:
    template: ${yaml:datasets/cifar100/test_noaug}
```
